# Generated by Django 3.2.24 on 2024-03-23 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_appointment_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app1.generatorprofile')),
                ('recycler_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app1.recyclerprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
